### PR TITLE
Migration to Scala 2.10.0-M6

### PR DESCRIPTION
**Pull request by danielkroeni**
Hi Heiko

I just upgraded your project for M6. I commented out the two plugins since sbt was unable to find them.
It would be nice if you could publish the jars to a maven repository.

Thanks
Daniel

### CODE REVIEW

**Comment by hseeberger** [comment]
Thanks for your contribution. Unfortunately I was already working on porting scalalogging to M6 as well as adding some improvements (testing, better build definition, etc.). Hence I cannot merge it, there would be too many conflicts.

You find the current 0.1.0-SNAPSHOT here: https://oss.sonatype.org/content/repositories/snapshots/name/heikoseeberger/scalalogging_2.10/0.1.0-SNAPSHOT/scalalogging_2.10-0.1.0-SNAPSHOT.jar

By the way: The sbt plugins are available, but you have to use sbt 0.12.0(RC4).

I am planning to switch from JUL to Logback. Any thoughts?

Cheers
Heiko

**Comment by danielkroeni** [comment]
> Thanks for your contribution. Unfortunately I was already working on
> porting scalalogging to M6 as well as adding some improvements (testing,
> better build definition, etc.). Hence I cannot merge it, there would be too
> many conflicts.

Fortunately for me I would say.

> You find the current 0.1.0-SNAPSHOT here:
> https://oss.sonatype.org/content/repositories/snapshots/name/heikoseeberger/scalalogging_2.10/0.1.0-SNAPSHOT/scalalogging_2.10-0.1.0-SNAPSHOT.jar

Many thanks!

> By the way: The sbt plugins are available, but you have to use sbt
> 0.12.0(RC4).

I think that's the version I have tried (the newest 0.12 xsbt build I've
found). I will try again.

> I am planning to switch from JUL to Logback. Any thoughts?

That's just perfect. A friend of mine started working on a log4j version
but logback fits our needs as well.

Is there a chance to get this officially published under an com.typesafe
naming schema? It's now the third logging-lib we use, because the
alternatives have stopped being maintained.

Cheers
Daniel

**Comment by hseeberger** [comment]
Daniel,

I discussed it with my colleagues and we might indeed move ScalaLogging under the com.typesafe organization.

Could you please elaborate why you are interested in that step?

Thanks
Heiko

**Comment by danielkroeni** [comment]
> I discussed it with my colleagues and we might indeed move ScalaLogging
> under the com.typesafe organization.
> 
> Could you please elaborate why you are interested in that step?

Sure.
We again lost some hours to find an up-to-date (2.10.0-M6) logging library.
Sometimes I think we should just write the few lines by ourselves. On the
other hand logging is something I (and maybe 5 million other scala devs)
need in every project and I just want to write one sbt dependency entry to
get it working.
It would give me the feel of an officially supported piece of code which I
can rely on. Don't get me wrong, Seeberger sounds trustworthy too :-). It's
just that typesafe is able to maintain a logging library even when Heiko is
on holiday.

Thanks
Daniel

**Comment by hseeberger** [comment]
"It's just that typesafe is able to maintain a logging library even when Heiko is on holiday." is just awesome ;-)

**Pull request closed without merging**
